package builtin

import (
	"fmt"
	"strings"

	"github.com/edlitmus/halite/internal/exec"
	"github.com/edlitmus/halite/internal/signature"
	"github.com/edlitmus/halite/internal/states"
	"github.com/edlitmus/halite/internal/value"
)

// registerCron installs the cron module.
//
// A managed crontab entry carries an identifying comment on the line
// above it, which is how the state finds its own entry again on the next
// run without matching on the command text. Salt does the same, and a
// tree that has been managed by Salt will have those comments already.
func registerCron(r *Registries) {
	cronParams := []signature.Param{
		nameParam("The command to run. Defaults to the state ID."),
		opt("user", signature.String, "root", "Whose crontab to manage."),
		opt("minute", signature.String, "*", "The minute field."),
		opt("hour", signature.String, "*", "The hour field."),
		opt("daymonth", signature.String, "*", "The day-of-month field."),
		opt("month", signature.String, "*", "The month field."),
		opt("dayweek", signature.String, "*", "The day-of-week field."),
		opt("identifier", signature.String, "", "The identifying comment; defaults to the command."),
		opt("comment", signature.String, "", "A human note kept with the entry."),
		opt("special", signature.String, "", "A @reboot-style shorthand, replacing the five fields."),
	}

	r.Exec.Add(
		exec.Module{
			Sig: signature.Signature{
				Module: "cron", Function: "raw_cron",
				Doc:      "Return an account's crontab as text.",
				Params:   []signature.Param{opt("user", signature.String, "root", "Whose crontab.")},
				TestMode: signature.TestNotApplicable,
				Section:  "15.2",
			},
			Fn: func(c *exec.Context, args *value.Map) (any, error) {
				return readCrontab(c, states.Str(args, "user", "root"))
			},
		},
		exec.Module{
			Sig: signature.Signature{
				Module: "cron", Function: "list_tab",
				Doc:      "Return an account's crontab as structured entries.",
				Params:   []signature.Param{opt("user", signature.String, "root", "Whose crontab.")},
				TestMode: signature.TestNotApplicable,
				Section:  "15.2",
			},
			Fn: func(c *exec.Context, args *value.Map) (any, error) {
				text, err := readCrontab(c, states.Str(args, "user", "root"))
				if err != nil {
					return nil, err
				}
				entries := parseCrontab(text)
				out := make([]any, 0, len(entries))
				for _, e := range entries {
					if e.Raw != "" {
						continue
					}
					out = append(out, value.MapOf(
						"identifier", e.Identifier,
						"spec", e.Spec,
						"cmd", e.Command,
						"comment", e.Comment,
					))
				}
				return out, nil
			},
		},
	)

	r.States.Add(
		states.Module{
			Sig: signature.Signature{
				Module: "cron", Function: "present",
				Doc:        "Ensure a crontab entry exists with the given schedule.",
				Params:     cronParams,
				Mutates:    true,
				TestMode:   signature.TestReliable,
				Privileges: []string{"the target account, or root"},
				Section:    "15.5",
			},
			Fn: cronPresent,
		},
		states.Module{
			Sig: signature.Signature{
				Module: "cron", Function: "absent",
				Doc: "Ensure a crontab entry does not exist.",
				Params: []signature.Param{
					nameParam("The command. Defaults to the state ID."),
					opt("user", signature.String, "root", "Whose crontab to manage."),
					opt("identifier", signature.String, "", "The identifying comment; defaults to the command."),
				},
				Mutates:    true,
				TestMode:   signature.TestReliable,
				Privileges: []string{"the target account, or root"},
				Section:    "15.5",
			},
			Fn: cronAbsent,
		},
	)
}

// cronEntry is one managed crontab line and the identifying comment above
// it.
type cronEntry struct {
	Identifier string
	Spec       string
	Command    string
	Comment    string
	// Raw holds a line the module did not write, preserved verbatim.
	Raw string
}

// managedMarker is the comment halite writes above an entry it owns. The
// spelling matches Salt's so that a crontab already managed by Salt is
// recognised rather than duplicated.
const managedMarker = "# Lines below here are managed by halite, do not edit"

const identifierPrefix = "#HALITE_CRON_IDENTIFIER:"

// legacyIdentifierPrefix is what Salt writes. It is recognised on read so
// that a crontab a Salt run already manages is adopted rather than
// duplicated, and rewritten with halite's own marker on the first change.
const legacyIdentifierPrefix = "#DO NOT EDIT THIS FILE - edit the master and reinstall." // lexicon:allow

func readCrontab(c *exec.Context, user string) (string, error) {
	res, err := c.Run(exec.Command{
		Argv:           []string{"crontab", "-u", user, "-l"},
		IgnoreExitCode: true,
	})
	if err != nil {
		return "", err
	}
	if res.Code != 0 {
		// A user with no crontab is not an error; both cron
		// implementations say so on stderr and exit non-zero.
		if strings.Contains(res.Stderr, "no crontab") {
			return "", nil
		}
		// FreeBSD's crontab has no -u for a non-root caller; retry
		// without it, which reads the caller's own crontab.
		res, err = c.Run(exec.Command{Argv: []string{"crontab", "-l"}, IgnoreExitCode: true})
		if err != nil {
			return "", err
		}
		if res.Code != 0 {
			if strings.Contains(res.Stderr, "no crontab") {
				return "", nil
			}
			return "", fmt.Errorf("reading the crontab for %s: %s", user, firstLine(res.Stderr))
		}
	}
	return res.Stdout, nil
}

func writeCrontab(c *exec.Context, user, text string) error {
	res, err := c.Run(exec.Command{
		Argv:           []string{"crontab", "-u", user, "-"},
		Stdin:          text,
		IgnoreExitCode: true,
	})
	if err != nil {
		return err
	}
	if res.Code == 0 {
		return nil
	}
	res, err = c.Run(exec.Command{Argv: []string{"crontab", "-"}, Stdin: text, IgnoreExitCode: true})
	if err != nil {
		return err
	}
	if res.Code != 0 {
		return fmt.Errorf("writing the crontab for %s: %s", user, firstLine(res.Stderr))
	}
	return nil
}

func parseCrontab(text string) []cronEntry {
	var out []cronEntry
	lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
	pendingID := ""
	pendingComment := ""

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, identifierPrefix):
			pendingID = strings.TrimSpace(strings.TrimPrefix(trimmed, identifierPrefix))
			continue
		case trimmed == managedMarker:
			continue
		case strings.HasPrefix(trimmed, "#"):
			if pendingID != "" {
				pendingComment = strings.TrimSpace(strings.TrimPrefix(trimmed, "#"))
				continue
			}
			out = append(out, cronEntry{Raw: line})
			continue
		case trimmed == "":
			out = append(out, cronEntry{Raw: line})
			continue
		}

		spec, command := splitCronLine(trimmed)
		id := pendingID
		if id == "" {
			id = command
		}
		out = append(out, cronEntry{Identifier: id, Spec: spec, Command: command, Comment: pendingComment})
		pendingID, pendingComment = "", ""
	}
	return out
}

// splitCronLine divides a crontab line into its schedule and its command.
func splitCronLine(line string) (spec, command string) {
	if strings.HasPrefix(line, "@") {
		fields := strings.SplitN(line, " ", 2)
		if len(fields) == 2 {
			return fields[0], strings.TrimSpace(fields[1])
		}
		return line, ""
	}
	// An environment assignment such as MAILTO= is not a schedule.
	if !strings.ContainsAny(line, " \t") {
		return "", line
	}
	fields := strings.Fields(line)
	if len(fields) < 6 {
		return "", line
	}
	spec = strings.Join(fields[:5], " ")
	// The command is the rest of the original line, so its internal
	// spacing survives.
	idx := 0
	seen := 0
	for i := 0; i < len(line) && seen < 5; i++ {
		if line[i] == ' ' || line[i] == '\t' {
			for i < len(line) && (line[i] == ' ' || line[i] == '\t') {
				i++
			}
			seen++
			idx = i
			i--
		}
	}
	return spec, strings.TrimSpace(line[idx:])
}

func renderCrontab(entries []cronEntry) string {
	var b strings.Builder
	for _, e := range entries {
		if e.Command == "" && e.Spec == "" {
			b.WriteString(e.Raw)
			b.WriteByte('\n')
			continue
		}
		if e.Identifier != "" && e.Identifier != e.Command {
			b.WriteString(identifierPrefix + " " + e.Identifier + "\n")
		}
		if e.Comment != "" {
			b.WriteString("# " + e.Comment + "\n")
		}
		if e.Spec != "" {
			b.WriteString(e.Spec + " ")
		}
		b.WriteString(e.Command)
		b.WriteByte('\n')
	}
	return b.String()
}

// cronSpec assembles the schedule from the five fields or the shorthand.
func cronSpec(args *value.Map) string {
	if special := states.Str(args, "special", ""); special != "" {
		if !strings.HasPrefix(special, "@") {
			return "@" + special
		}
		return special
	}
	return strings.Join([]string{
		states.Str(args, "minute", "*"),
		states.Str(args, "hour", "*"),
		states.Str(args, "daymonth", "*"),
		states.Str(args, "month", "*"),
		states.Str(args, "dayweek", "*"),
	}, " ")
}

func cronPresent(c *exec.Context, args *value.Map) (states.Result, error) {
	user := states.Str(args, "user", "root")
	command := states.Str(args, "name", "")
	if command == "" {
		return states.False("This state needs a command to run."), nil
	}
	identifier := states.Str(args, "identifier", "")
	if identifier == "" {
		identifier = command
	}
	want := cronEntry{
		Identifier: identifier,
		Spec:       cronSpec(args),
		Command:    command,
		Comment:    states.Str(args, "comment", ""),
	}

	text, err := readCrontab(c, user)
	if err != nil {
		return states.False(fmt.Sprintf("%v", err)), nil
	}
	entries := parseCrontab(text)

	found := false
	changed := false
	var old cronEntry
	for i := range entries {
		if entries[i].Identifier != identifier {
			continue
		}
		found = true
		old = entries[i]
		if entries[i].Spec != want.Spec || entries[i].Command != want.Command || entries[i].Comment != want.Comment {
			entries[i] = want
			changed = true
		}
		break
	}
	if !found {
		entries = append(entries, want)
		changed = true
	}

	if !changed {
		return states.True(fmt.Sprintf("The crontab entry for %s is already in place.", identifier)), nil
	}

	var oldDesc any
	if found {
		oldDesc = strings.TrimSpace(old.Spec + " " + old.Command)
	}
	changes := value.MapOf(identifier, states.Change(oldDesc, strings.TrimSpace(want.Spec+" "+want.Command)))

	verb := "updated"
	if !found {
		verb = "added"
	}
	if c.Test {
		return states.WouldChange(
			fmt.Sprintf("The crontab entry for %s would be %s in %s's crontab.", identifier, verb, user), changes), nil
	}
	if err := writeCrontab(c, user, renderCrontab(entries)); err != nil {
		return states.False(fmt.Sprintf("%v", err)), nil
	}
	return states.Changed(
		fmt.Sprintf("The crontab entry for %s was %s in %s's crontab.", identifier, verb, user), changes), nil
}

func cronAbsent(c *exec.Context, args *value.Map) (states.Result, error) {
	user := states.Str(args, "user", "root")
	identifier := states.Str(args, "identifier", "")
	if identifier == "" {
		identifier = states.Str(args, "name", "")
	}
	if identifier == "" {
		return states.False("This state needs a command or an identifier."), nil
	}

	text, err := readCrontab(c, user)
	if err != nil {
		return states.False(fmt.Sprintf("%v", err)), nil
	}
	entries := parseCrontab(text)

	kept := make([]cronEntry, 0, len(entries))
	var removed *cronEntry
	for _, e := range entries {
		if e.Identifier == identifier {
			copy := e
			removed = &copy
			continue
		}
		kept = append(kept, e)
	}
	if removed == nil {
		return states.True(fmt.Sprintf("%s's crontab already has no entry for %s.", user, identifier)), nil
	}

	changes := value.MapOf(identifier, states.Change(strings.TrimSpace(removed.Spec+" "+removed.Command), nil))
	if c.Test {
		return states.WouldChange(
			fmt.Sprintf("The crontab entry for %s would be removed from %s's crontab.", identifier, user), changes), nil
	}
	if err := writeCrontab(c, user, renderCrontab(kept)); err != nil {
		return states.False(fmt.Sprintf("%v", err)), nil
	}
	return states.Changed(
		fmt.Sprintf("The crontab entry for %s was removed from %s's crontab.", identifier, user), changes), nil
}
