package builtin

import (
	"runtime"
	"strings"
	"testing"

	"github.com/edlitmus/halite/internal/exec"
	"github.com/edlitmus/halite/internal/value"
)

// A real iptables-save, captured from iptables 1.8.10 (nf_tables) inside
// a network namespace. The bracketed counters are runtime state and the
// parser drops them.
const iptablesSaveSample = `# Generated by iptables-save v1.8.10 (nf_tables) on Thu Sep 10 12:18:19 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:halite-in - [0:0]
-A INPUT -p tcp -m tcp --dport 22 -m comment --comment "halite:ssh" -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -j halite-in
-A halite-in -s 10.0.0.0/8 -j DROP
COMMIT
# Completed on Thu Sep 10 12:18:19 2026
`

func TestIPTablesParsesSaveOutput(t *testing.T) {
	rs, err := iptablesParseSave(iptablesSaveSample)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	filter := rs.Tables["filter"]
	if filter == nil {
		t.Fatal("no filter table parsed")
	}
	if got := filter.Chains["INPUT"].Policy; got != "ACCEPT" {
		t.Errorf("INPUT policy = %q, want ACCEPT", got)
	}
	if got := filter.Chains["FORWARD"].Policy; got != "DROP" {
		t.Errorf("FORWARD policy = %q, want DROP", got)
	}
	// A user chain has no policy, and that is how the module tells a
	// built-in chain from a user one.
	if got := filter.Chains["halite-in"].Policy; got != "" {
		t.Errorf("user chain halite-in has policy %q, want none", got)
	}
	if n := len(filter.Chains["INPUT"].Rules); n != 3 {
		t.Fatalf("INPUT has %d rules, want 3", n)
	}
	if got := filter.Chains["INPUT"].Rules[0]; got != `-p tcp -m tcp --dport 22 -m comment --comment "halite:ssh" -j ACCEPT` {
		t.Errorf("first INPUT rule parsed as %q", got)
	}
	if got := filter.Chains["halite-in"].Rules[0]; got != "-s 10.0.0.0/8 -j DROP" {
		t.Errorf("halite-in rule parsed as %q", got)
	}
	// The counters in brackets are gone.
	if strings.Contains(strings.Join(filter.Chains["INPUT"].Rules, " "), "[") {
		t.Error("a byte counter survived the parse")
	}
}

func TestIPTablesBinForFamily(t *testing.T) {
	for family, want := range map[string]string{"ipv4": "iptables", "": "iptables", "ipv6": "ip6tables"} {
		got, err := iptablesBin(family)
		if err != nil || got != want {
			t.Errorf("iptablesBin(%q) = %q, %v; want %q", family, got, err, want)
		}
	}
	if _, err := iptablesBin("ipv5"); err == nil {
		t.Error("a bogus family was accepted")
	}
}

// build_rule assembles a spec in a fixed order so `iptables -C` sees the
// same string every run.
func TestIPTablesBuildRule(t *testing.T) {
	args := value.MapOf(
		"protocol", "tcp",
		"dport", "22",
		"source", "10.0.0.0/8",
		"ctstate", "NEW",
		"comment", "ssh from the bastion",
		"jump", "ACCEPT",
	)
	got := strings.Join(iptablesBuildRule(args), " ")
	want := `-s 10.0.0.0/8 -p tcp -m conntrack --ctstate NEW --dport 22 -m comment --comment ssh from the bastion -j ACCEPT`
	if got != want {
		t.Errorf("build_rule =\n  %s\nwant\n  %s", got, want)
	}

	// Order is stable regardless of the order the keys were given in.
	args2 := value.MapOf("jump", "DROP", "dport", "80", "protocol", "tcp")
	if a, b := strings.Join(iptablesBuildRule(args2), " "), "-p tcp --dport 80 -j DROP"; a != b {
		t.Errorf("build_rule = %q, want %q", a, b)
	}
}

// A quoted run in a rule string stays one token, so `--comment "a b"`
// reaches iptables as the single argument it made its match on.
func TestSplitRuleSpec(t *testing.T) {
	got := splitRuleSpec(`-p tcp --dport 22 -m comment --comment "ssh from bastion" -j ACCEPT`)
	want := []string{"-p", "tcp", "--dport", "22", "-m", "comment", "--comment", "ssh from bastion", "-j", "ACCEPT"}
	if len(got) != len(want) {
		t.Fatalf("split into %d tokens %q, want %d", len(got), got, len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("token %d = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestIPTablesSpecFromArgs(t *testing.T) {
	// A literal string.
	spec, err := iptablesSpecFromArgs(value.MapOf("rule", "-p tcp --dport 22 -j ACCEPT"))
	if err != nil || strings.Join(spec, " ") != "-p tcp --dport 22 -j ACCEPT" {
		t.Errorf("string rule = %q, %v", spec, err)
	}
	// A token list.
	spec, err = iptablesSpecFromArgs(value.MapOf("rule", []any{"-p", "udp", "--dport", "53", "-j", "ACCEPT"}))
	if err != nil || strings.Join(spec, " ") != "-p udp --dport 53 -j ACCEPT" {
		t.Errorf("list rule = %q, %v", spec, err)
	}
	// Built from parts.
	spec, err = iptablesSpecFromArgs(value.MapOf("protocol", "icmp", "jump", "DROP"))
	if err != nil || strings.Join(spec, " ") != "-p icmp -j DROP" {
		t.Errorf("parts rule = %q, %v", spec, err)
	}
	// Nothing at all.
	if _, err := iptablesSpecFromArgs(value.NewMap(0)); err == nil {
		t.Error("an empty rule was accepted")
	}
}

// ---- behaviour, on a scripted runner ----

func iptablesCtx(responses map[string]exec.Result) *exec.Context {
	return &exec.Context{
		Runner: &exec.RecordingRunner{Responses: responses},
		Lookup: func(name string) string { return "/usr/sbin/" + name },
	}
}

func iptablesSaveKey() string {
	return (exec.Command{Argv: []string{"iptables-save"}}).String()
}

// append checks with -C first and only runs -A when the rule is absent.
func TestIPTablesAppendIsIdempotent(t *testing.T) {
	present := "iptables -t filter -C INPUT -p tcp --dport 22 -j ACCEPT"

	// -C exits 0: the rule is there, nothing runs.
	c := iptablesCtx(map[string]exec.Result{present: {Code: 0}})
	out, err := iptablesAddRule(c, value.MapOf("chain", "INPUT", "rule", "-p tcp --dport 22 -j ACCEPT"), "append")
	if err != nil {
		t.Fatal(err)
	}
	if changed, _ := out.(*value.Map).GetString("changed"); changed != false {
		t.Errorf("append of an existing rule reported a change: %v", out)
	}
	for _, ran := range c.Runner.(*exec.RecordingRunner).RanCommands() {
		if strings.Contains(ran, "-A INPUT") {
			t.Errorf("append ran %q when the rule was already present", ran)
		}
	}

	// -C exits 1: the rule is absent, -A runs.
	c2 := iptablesCtx(map[string]exec.Result{present: {Code: 1}})
	out, err = iptablesAddRule(c2, value.MapOf("chain", "INPUT", "rule", "-p tcp --dport 22 -j ACCEPT"), "append")
	if err != nil {
		t.Fatal(err)
	}
	if changed, _ := out.(*value.Map).GetString("changed"); changed != true {
		t.Errorf("append of a missing rule reported no change: %v", out)
	}
	var appended bool
	for _, ran := range c2.Runner.(*exec.RecordingRunner).RanCommands() {
		if ran == "iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT" {
			appended = true
		}
	}
	if !appended {
		t.Errorf("append did not run -A: %v", c2.Runner.(*exec.RecordingRunner).RanCommands())
	}

	// Test mode predicts the change and runs no -A.
	c3 := iptablesCtx(map[string]exec.Result{present: {Code: 1}})
	c3.Test = true
	out, _ = iptablesAddRule(c3, value.MapOf("chain", "INPUT", "rule", "-p tcp --dport 22 -j ACCEPT"), "append")
	if changed, _ := out.(*value.Map).GetString("changed"); changed != true {
		t.Errorf("test mode did not predict the change: %v", out)
	}
	for _, ran := range c3.Runner.(*exec.RecordingRunner).RanCommands() {
		if strings.Contains(ran, "-A INPUT") {
			t.Errorf("a test run executed %q", ran)
		}
	}
}

// flush refuses to strip a built-in chain that is holding traffic out,
// and refuses a whole-table flush, unless force is set.
func TestIPTablesFlushRefusesADangerousFlush(t *testing.T) {
	responses := map[string]exec.Result{iptablesSaveKey(): {Stdout: iptablesSaveSample}}

	// INPUT is ACCEPT in the sample, so flushing it is allowed -- swap in
	// a sample where it is DROP.
	dropInput := strings.Replace(iptablesSaveSample, ":INPUT ACCEPT [0:0]", ":INPUT DROP [0:0]", 1)
	c := iptablesCtx(map[string]exec.Result{iptablesSaveKey(): {Stdout: dropInput}})
	if _, err := iptablesFlushFn(c, value.MapOf("chain", "INPUT")); err == nil {
		t.Error("flushing a DROP-policy INPUT chain was allowed without force")
	} else if !strings.Contains(err.Error(), "off the network") {
		t.Errorf("the refusal does not explain the danger: %v", err)
	}
	// With force it goes ahead.
	c2 := iptablesCtx(map[string]exec.Result{iptablesSaveKey(): {Stdout: dropInput}})
	c2.Test = true
	if _, err := iptablesFlushFn(c2, value.MapOf("chain", "INPUT", "force", true)); err != nil {
		t.Errorf("a forced flush was refused: %v", err)
	}

	// A whole-table flush needs force too.
	c3 := iptablesCtx(responses)
	if _, err := iptablesFlushFn(c3, value.NewMap(0)); err == nil {
		t.Error("a whole-table flush was allowed without force")
	}

	// A user-defined chain has no policy and flushing one is fine.
	c4 := iptablesCtx(responses)
	c4.Test = true
	out, err := iptablesFlushFn(c4, value.MapOf("chain", "halite-in"))
	if err != nil {
		t.Fatalf("flushing a user chain was refused: %v", err)
	}
	if changed, _ := out.(*value.Map).GetString("changed"); changed != true {
		t.Errorf("flushing a user chain with a rule in it reported no change: %v", out)
	}
}

// set_policy is idempotent and only touches built-in chains.
func TestIPTablesSetPolicy(t *testing.T) {
	c := iptablesCtx(map[string]exec.Result{iptablesSaveKey(): {Stdout: iptablesSaveSample}})
	// FORWARD is already DROP in the sample.
	out, _, err := iptablesSetPolicy(c, value.MapOf("chain", "FORWARD", "policy", "DROP"))
	if err != nil {
		t.Fatal(err)
	}
	if changed, _ := out.GetString("changed"); changed != false {
		t.Errorf("setting FORWARD to the policy it already has reported a change: %v", out)
	}

	// A user chain has no policy to set.
	c2 := iptablesCtx(map[string]exec.Result{iptablesSaveKey(): {Stdout: iptablesSaveSample}})
	if _, _, err := iptablesSetPolicy(c2, value.MapOf("chain", "halite-in", "policy", "DROP")); err == nil {
		t.Error("set_policy accepted a user-defined chain")
	}
}

func TestIPTablesRefusesWithoutTheTools(t *testing.T) {
	c := &exec.Context{Runner: &exec.RecordingRunner{}, Lookup: func(string) string { return "" }}
	if _, err := iptablesReadRuleset(c, "ipv4"); err == nil || !strings.Contains(err.Error(), "iptables") {
		t.Errorf("the refusal does not name the package: %v", err)
	}
}

func TestIPTablesRefusesOnANonLinuxPlatform(t *testing.T) {
	if runtime.GOOS == "linux" {
		t.Skip("this is about the platforms iptables is not declared for")
	}
	_, err := New().Exec.Call(&exec.Context{}, "iptables.get_rules", value.NewMap(0))
	if err == nil || !strings.Contains(err.Error(), "this node is "+runtime.GOOS) {
		t.Errorf("iptables.get_rules did not refuse by platform: %v", err)
	}
}
