package ca

import (
	"crypto"
	"crypto/x509"
	"encoding/pem"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func newStore(t *testing.T) *Store {
	t.Helper()
	s := &Store{Dir: t.TempDir()}
	if err := s.Init("halite test ca", 10*365*24*time.Hour); err != nil {
		t.Fatalf("init: %v", err)
	}
	return s
}

// csrFor returns a CSR for id, generated by a fresh key.
func csrFor(t *testing.T, id string) []byte {
	t.Helper()
	key, _, err := GenerateKey()
	if err != nil {
		t.Fatal(err)
	}
	csrPEM, err := NewCSR(key, id, nil)
	if err != nil {
		t.Fatal(err)
	}
	return csrPEM
}

func TestInitRefusesToOverwriteAnExistingCA(t *testing.T) {
	s := newStore(t)
	err := s.Init("halite test ca", time.Hour)
	if err == nil {
		t.Fatal("re-initializing must fail rather than replace the CA")
	}
	if !strings.Contains(err.Error(), "refusing") {
		t.Errorf("unhelpful error: %v", err)
	}
}

func TestCAKeyIsNotWorldReadable(t *testing.T) {
	s := newStore(t)
	info, err := os.Stat(filepath.Join(s.Dir, "ca.key"))
	if err != nil {
		t.Fatal(err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("ca.key mode is %04o, want 0600", mode)
	}
}

func TestAcceptedAgentCertVerifiesAgainstTheCA(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatalf("submit: %v", err)
	}
	certPEM, err := s.Accept("web1")
	if err != nil {
		t.Fatalf("accept: %v", err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}

	caPEM, err := s.CACertPEM()
	if err != nil {
		t.Fatal(err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		t.Fatal("ca certificate did not parse into a pool")
	}
	if _, err := cert.Verify(x509.VerifyOptions{
		Roots:     pool,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}); err != nil {
		t.Errorf("agent certificate does not chain to the CA: %v", err)
	}
	if cert.Subject.CommonName != "web1" {
		t.Errorf("common name = %q, want web1", cert.Subject.CommonName)
	}
}

func TestAgentCertCannotBeUsedForServerAuth(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	certPEM, err := s.Accept("web1")
	if err != nil {
		t.Fatal(err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}
	for _, usage := range cert.ExtKeyUsage {
		if usage == x509.ExtKeyUsageServerAuth {
			t.Fatal("an agent certificate must not be valid for server auth")
		}
	}
}

func TestSubmitIgnoresTheRequestedIdentity(t *testing.T) {
	s := newStore(t)
	// A host asking to be "master" while calling itself web1 must be refused:
	// the identity in the request has to match the identity it enrolls as.
	if _, err := s.Submit("web1", csrFor(t, "master")); err == nil {
		t.Fatal("a CSR whose common name differs from the id must be rejected")
	}
}

func TestSubmitRejectsUnsafeIdentities(t *testing.T) {
	s := newStore(t)
	for _, id := range []string{"../escape", "a/b", "", ".hidden", strings.Repeat("x", 65)} {
		if _, err := s.Submit(id, csrFor(t, id)); err == nil {
			t.Errorf("id %q must be rejected", id)
		}
	}
	if entries, _ := s.List(); len(entries) != 0 {
		t.Errorf("rejected ids must not be stored: %v", entries)
	}
}

func TestResubmitIsIdempotentButKeySwapIsRefused(t *testing.T) {
	s := newStore(t)
	csrPEM := csrFor(t, "web1")
	if _, err := s.Submit("web1", csrPEM); err != nil {
		t.Fatal(err)
	}
	state, err := s.Submit("web1", csrPEM)
	if err != nil {
		t.Fatalf("re-submitting the same request must be a no-op: %v", err)
	}
	if state != StatePending {
		t.Errorf("state = %q, want pending", state)
	}
	if _, err := s.Submit("web1", csrFor(t, "web1")); err == nil {
		t.Fatal("a second, different key for a known id must be refused")
	}
}

func TestSubmitRefusesNewIdentitiesOverThePendingCap(t *testing.T) {
	s := newStore(t)
	firstCSR := csrFor(t, "web1")
	if _, err := s.SubmitLimited("web1", firstCSR, 2); err != nil {
		t.Fatal(err)
	}
	if _, err := s.SubmitLimited("web2", csrFor(t, "web2"), 2); err != nil {
		t.Fatal(err)
	}

	// The cap is reached; a third identity must be turned away with the
	// error the control plane matches on, and nothing stored for it.
	_, err := s.SubmitLimited("web3", csrFor(t, "web3"), 2)
	if !errors.Is(err, ErrPendingFull) {
		t.Fatalf("over the cap got %v, want ErrPendingFull", err)
	}
	if _, statErr := os.Stat(filepath.Join(s.Dir, "pending", "web3.csr")); statErr == nil {
		t.Error("a refused request must not be stored")
	}

	// A retry from an already-pending agent is not a new identity and must
	// keep getting its honest answer at the cap.
	state, err := s.SubmitLimited("web1", firstCSR, 2)
	if err != nil || state != StatePending {
		t.Errorf("retry at the cap: state=%q err=%v", state, err)
	}

	// Deciding a request frees its slot.
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}
	if _, err := s.SubmitLimited("web3", csrFor(t, "web3"), 2); err != nil {
		t.Errorf("after accepting one, a new enrollment must fit: %v", err)
	}
}

func TestSubmitAfterAcceptReportsAccepted(t *testing.T) {
	s := newStore(t)
	csrPEM := csrFor(t, "web1")
	if _, err := s.Submit("web1", csrPEM); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}
	state, err := s.Submit("web1", csrPEM)
	if err != nil {
		t.Fatalf("submit after accept: %v", err)
	}
	if state != StateAccepted {
		t.Errorf("state = %q, want accepted", state)
	}
}

// TestAcceptedIdentityDoesNotHandOutItsCertificateToAnotherKey covers the
// one route that answers before authentication: a caller who guesses an
// accepted id must not learn that it exists, let alone receive its
// certificate, by submitting a key of their own.
func TestAcceptedIdentityDoesNotHandOutItsCertificateToAnotherKey(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}

	state, err := s.Submit("web1", csrFor(t, "web1"))
	if err == nil {
		t.Fatalf("an attacker's key for an accepted id returned %q instead of an error", state)
	}
	if !strings.Contains(err.Error(), "web1") {
		t.Errorf("the error should name the id: %v", err)
	}
}

// TestAcceptedIdentityWithNoArchivedRequestIsRefused is the fail-closed
// half: an entry whose CSR somebody deleted by hand cannot be compared,
// so it is refused rather than trusted.
func TestAcceptedIdentityWithNoArchivedRequestIsRefused(t *testing.T) {
	s := newStore(t)
	csrPEM := csrFor(t, "web1")
	if _, err := s.Submit("web1", csrPEM); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(s.path("accepted", "web1.csr")); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Submit("web1", csrPEM); err == nil {
		t.Fatal("an accepted id with no request on file must not be answered")
	}
}

func TestAcceptIsStableAcrossCalls(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	first, err := s.Accept("web1")
	if err != nil {
		t.Fatal(err)
	}
	second, err := s.Accept("web1")
	if err != nil {
		t.Fatalf("re-accepting must return the issued certificate: %v", err)
	}
	if string(first) != string(second) {
		t.Error("accepting twice issued two different certificates")
	}
}

func TestRejectedIdentityIsNotIssuedACertificate(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if err := s.Reject("web1"); err != nil {
		t.Fatalf("reject: %v", err)
	}
	if _, err := s.Accept("web1"); err == nil {
		t.Fatal("a rejected identity must not be acceptable without an operator removing it")
	}
	if _, err := s.IssuedCert("web1"); err == nil {
		t.Fatal("a rejected identity must have no certificate")
	}
}

func TestRemoveLetsAnIdentityStartOver(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if err := s.Reject("web1"); err != nil {
		t.Fatal(err)
	}
	if err := s.Remove("web1"); err != nil {
		t.Fatalf("remove: %v", err)
	}
	state, err := s.Submit("web1", csrFor(t, "web1"))
	if err != nil {
		t.Fatalf("re-enrolling a removed id: %v", err)
	}
	if state != StatePending {
		t.Errorf("state = %q, want pending", state)
	}
}

func TestListReportsStateAndFingerprint(t *testing.T) {
	s := newStore(t)
	pendingCSR := csrFor(t, "db1")
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Submit("db1", pendingCSR); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}

	entries, err := s.List()
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("got %d entries, want 2: %v", len(entries), entries)
	}
	byID := map[string]Entry{}
	for _, e := range entries {
		byID[e.ID] = e
	}
	if byID["web1"].State != StateAccepted || byID["db1"].State != StatePending {
		t.Errorf("wrong states: %v", entries)
	}
	// The accepted certificate must carry the same key the request had.
	want, err := CSRFingerprint(pendingCSR)
	if err != nil {
		t.Fatal(err)
	}
	if byID["db1"].Fingerprint != want {
		t.Errorf("fingerprint = %q, want %q", byID["db1"].Fingerprint, want)
	}
	if byID["web1"].Fingerprint == "" {
		t.Error("accepted entry has no fingerprint")
	}
}

func TestServerCertificateCarriesItsSANs(t *testing.T) {
	s := newStore(t)
	if err := s.IssueServer("master.example.com", []string{"master.example.com", "10.0.0.1"}, time.Hour); err != nil {
		t.Fatalf("issue server: %v", err)
	}
	certPEM, err := os.ReadFile(filepath.Join(s.Dir, "master.crt"))
	if err != nil {
		t.Fatal(err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}
	if len(cert.DNSNames) != 1 || cert.DNSNames[0] != "master.example.com" {
		t.Errorf("dns names = %v", cert.DNSNames)
	}
	if len(cert.IPAddresses) != 1 || cert.IPAddresses[0].String() != "10.0.0.1" {
		t.Errorf("ip sans = %v", cert.IPAddresses)
	}
	info, err := os.Stat(filepath.Join(s.Dir, "master.key"))
	if err != nil {
		t.Fatal(err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("master.key mode is %04o, want 0600", mode)
	}
}

func TestTamperedCSRIsRejected(t *testing.T) {
	s := newStore(t)
	block, _ := pem.Decode(csrFor(t, "web1"))
	if block == nil {
		t.Fatal("generated CSR is not PEM")
	}
	// Corrupt the trailing signature bytes: the structure still parses, but
	// the requester can no longer prove it holds the private key.
	block.Bytes[len(block.Bytes)-1] ^= 0xff
	tampered := pem.EncodeToMemory(block)

	if _, err := s.Submit("web1", tampered); err == nil {
		t.Fatal("a CSR that fails signature verification must be rejected")
	}
}

// renewable returns a store holding an accepted identity whose certificate
// is nearly out of time, plus the key it belongs to.
func renewable(t *testing.T, id string, remaining time.Duration) (*Store, crypto.Signer, []byte) {
	t.Helper()
	s := newStore(t)
	key, _, err := GenerateKey()
	if err != nil {
		t.Fatal(err)
	}
	csrPEM, err := NewCSR(key, id, nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := s.Submit(id, csrPEM); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept(id); err != nil {
		t.Fatal(err)
	}
	// Accept issues a full year. Replace it with one that is nearly up, so
	// the test is about renewal rather than about the clock.
	expiring, err := s.Sign(csrPEM, id, RoleAgent, nil, remaining)
	if err != nil {
		t.Fatal(err)
	}
	if err := ReplaceFile(s.path("accepted", id+".crt"), expiring, 0o644); err != nil {
		t.Fatal(err)
	}
	return s, key, csrPEM
}

func TestRenewIssuesAFullLifetimeForTheSameKey(t *testing.T) {
	s, key, _ := renewable(t, "web1", time.Hour)

	// A renewal carries a fresh request for the key the agent still holds.
	csrPEM, err := NewCSR(key, "web1", nil)
	if err != nil {
		t.Fatal(err)
	}
	renewedPEM, err := s.Renew("web1", csrPEM)
	if err != nil {
		t.Fatalf("renew: %v", err)
	}
	renewed, err := parseCertPEM(renewedPEM)
	if err != nil {
		t.Fatal(err)
	}
	if remaining := time.Until(renewed.NotAfter); remaining < AgentCertLifetime-time.Minute {
		t.Errorf("renewed certificate expires in %s, want about %s", remaining, AgentCertLifetime)
	}
	if !samePublicKey(renewed.PublicKey, key.Public()) {
		t.Error("the renewed certificate is for a different key")
	}
	// The store must hand out the new one from now on, or the next
	// enrollment check compares against a certificate nobody holds.
	stored, err := os.ReadFile(s.path("accepted", "web1.crt"))
	if err != nil {
		t.Fatal(err)
	}
	if string(stored) != string(renewedPEM) {
		t.Error("accepted/web1.crt still holds the old certificate")
	}
}

func TestRenewRefusesADifferentKey(t *testing.T) {
	s, _, _ := renewable(t, "web1", time.Hour)

	// A stolen certificate must not be a way to swap in a key an operator
	// never saw: that is an enrollment, and the CA has no revocation list
	// to take the result back with.
	if _, err := s.Renew("web1", csrFor(t, "web1")); err == nil {
		t.Fatal("renewal with a new key must be refused")
	}
}

func TestRenewRefusesUnknownAndMismatchedIdentities(t *testing.T) {
	s, key, _ := renewable(t, "web1", time.Hour)

	if _, err := s.Renew("web2", csrFor(t, "web2")); err == nil {
		t.Error("renewing an identity with no certificate must fail")
	}
	otherName, err := NewCSR(key, "web2", nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := s.Renew("web1", otherName); err == nil {
		t.Error("a request whose common name is another id must be refused")
	}
}

// expire replaces an accepted identity's certificate with one that has
// already run out, which is the state a host switched off for a year
// comes back to.
func expire(t *testing.T, s *Store, id string) {
	t.Helper()
	csrPEM, err := os.ReadFile(s.path("accepted", id+".csr"))
	if err != nil {
		t.Fatal(err)
	}
	stale, err := s.Sign(csrPEM, id, RoleAgent, nil, -30*time.Minute)
	if err != nil {
		t.Fatal(err)
	}
	if err := ReplaceFile(s.path("accepted", id+".crt"), stale, 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestReissueExpiredOnlyActsOnAnExpiredCertificate(t *testing.T) {
	s, _, _ := renewable(t, "web1", time.Hour)

	certPEM, reissued, err := s.ReissueExpired("web1")
	if err != nil {
		t.Fatal(err)
	}
	if reissued {
		t.Error("a certificate with an hour left must not be reissued: renewal is the authenticated way to replace it")
	}
	onFile, err := s.IssuedCert("web1")
	if err != nil || string(onFile) != string(certPEM) {
		t.Error("the certificate on file should have been returned unchanged")
	}

	expire(t, s, "web1")
	fresh, reissued, err := s.ReissueExpired("web1")
	if err != nil {
		t.Fatal(err)
	}
	if !reissued {
		t.Fatal("an expired certificate must be reissued; the host cannot renew with it")
	}
	cert, err := parseCertPEM(fresh)
	if err != nil {
		t.Fatal(err)
	}
	if remaining := time.Until(cert.NotAfter); remaining < AgentCertLifetime-time.Minute {
		t.Errorf("reissued certificate expires in %s, want about %s", remaining, AgentCertLifetime)
	}
	// It has to be for the accepted key, which is what makes issuing it to
	// an unauthenticated caller harmless: nobody else holds that key.
	original, err := os.ReadFile(s.path("accepted", "web1.csr"))
	if err != nil {
		t.Fatal(err)
	}
	csr, err := ParseCSR(original)
	if err != nil {
		t.Fatal(err)
	}
	if !samePublicKey(cert.PublicKey, csr.PublicKey) {
		t.Error("the reissued certificate is for a different key than the accepted request")
	}
	if stored, _ := s.IssuedCert("web1"); string(stored) != string(fresh) {
		t.Error("the store still holds the expired certificate")
	}
}

func TestReissueExpiredNeedsAnAcceptedIdentity(t *testing.T) {
	s := newStore(t)
	if _, _, err := s.ReissueExpired("web1"); err == nil {
		t.Error("an identity nobody accepted has nothing to reissue")
	}
}

func TestRevokeDeniesAnIdentityUntilItIsRemoved(t *testing.T) {
	s, _, csrPEM := renewable(t, "web1", time.Hour)
	if s.IsRevoked("web1") {
		t.Fatal("an accepted identity is not revoked")
	}

	if err := s.Revoke("web1"); err != nil {
		t.Fatal(err)
	}
	if !s.IsRevoked("web1") {
		t.Fatal("revoke did not take")
	}
	// Nothing is left to renew or reissue from: the certificate and the
	// request move out of accepted together.
	if _, err := s.IssuedCert("web1"); err == nil {
		t.Error("a revoked identity must not have an issued certificate on file")
	}
	if _, err := s.Renew("web1", csrPEM); err == nil {
		t.Error("a revoked identity must not renew")
	}
	if _, _, err := s.ReissueExpired("web1"); err == nil {
		t.Error("a revoked identity must not be reissued")
	}

	// Enrolling again is refused rather than filed as a new request, so
	// `key accept -all` cannot quietly let it back in.
	state, err := s.Submit("web1", csrPEM)
	if err == nil && state == StatePending {
		t.Fatal("a revoked identity must not become pending again")
	}
	if entries, _ := s.List(); len(entries) != 1 || entries[0].State != StateRevoked {
		t.Errorf("key list should show it as revoked: %+v", entries)
	}

	// Removing is the way back, and it starts over needing an operator.
	if err := s.Remove("web1"); err != nil {
		t.Fatal(err)
	}
	if s.IsRevoked("web1") {
		t.Fatal("remove must clear the revocation, or the host can never come back")
	}
	if state, err := s.Submit("web1", csrPEM); err != nil || state != StatePending {
		t.Errorf("after remove, enrolling starts over: state=%q err=%v", state, err)
	}
}

func TestRevokeNeedsAnAcceptedIdentity(t *testing.T) {
	s := newStore(t)
	if err := s.Revoke("web1"); err == nil {
		t.Error("there is nothing to revoke for an unknown id")
	}
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if err := s.Revoke("web1"); err == nil {
		t.Error("a pending request is rejected, not revoked")
	}
}

func TestRevokeTwiceIsAnError(t *testing.T) {
	s, _, _ := renewable(t, "web1", time.Hour)
	if err := s.Revoke("web1"); err != nil {
		t.Fatal(err)
	}
	if err := s.Revoke("web1"); err == nil {
		t.Error("revoking twice should say it is already revoked")
	}
}
