package ca

import (
	"crypto/x509"
	"encoding/pem"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func newStore(t *testing.T) *Store {
	t.Helper()
	s := &Store{Dir: t.TempDir()}
	if err := s.Init("halite test ca", 10*365*24*time.Hour); err != nil {
		t.Fatalf("init: %v", err)
	}
	return s
}

// csrFor returns a CSR for id, generated by a fresh key.
func csrFor(t *testing.T, id string) []byte {
	t.Helper()
	key, _, err := GenerateKey()
	if err != nil {
		t.Fatal(err)
	}
	csrPEM, err := NewCSR(key, id, nil)
	if err != nil {
		t.Fatal(err)
	}
	return csrPEM
}

func TestInitRefusesToOverwriteAnExistingCA(t *testing.T) {
	s := newStore(t)
	err := s.Init("halite test ca", time.Hour)
	if err == nil {
		t.Fatal("re-initializing must fail rather than replace the CA")
	}
	if !strings.Contains(err.Error(), "refusing") {
		t.Errorf("unhelpful error: %v", err)
	}
}

func TestCAKeyIsNotWorldReadable(t *testing.T) {
	s := newStore(t)
	info, err := os.Stat(filepath.Join(s.Dir, "ca.key"))
	if err != nil {
		t.Fatal(err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("ca.key mode is %04o, want 0600", mode)
	}
}

func TestAcceptedAgentCertVerifiesAgainstTheCA(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatalf("submit: %v", err)
	}
	certPEM, err := s.Accept("web1")
	if err != nil {
		t.Fatalf("accept: %v", err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}

	caPEM, err := s.CACertPEM()
	if err != nil {
		t.Fatal(err)
	}
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM(caPEM) {
		t.Fatal("ca certificate did not parse into a pool")
	}
	if _, err := cert.Verify(x509.VerifyOptions{
		Roots:     pool,
		KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
	}); err != nil {
		t.Errorf("agent certificate does not chain to the CA: %v", err)
	}
	if cert.Subject.CommonName != "web1" {
		t.Errorf("common name = %q, want web1", cert.Subject.CommonName)
	}
}

func TestAgentCertCannotBeUsedForServerAuth(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	certPEM, err := s.Accept("web1")
	if err != nil {
		t.Fatal(err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}
	for _, usage := range cert.ExtKeyUsage {
		if usage == x509.ExtKeyUsageServerAuth {
			t.Fatal("an agent certificate must not be valid for server auth")
		}
	}
}

func TestSubmitIgnoresTheRequestedIdentity(t *testing.T) {
	s := newStore(t)
	// A host asking to be "master" while calling itself web1 must be refused:
	// the identity in the request has to match the identity it enrolls as.
	if _, err := s.Submit("web1", csrFor(t, "master")); err == nil {
		t.Fatal("a CSR whose common name differs from the id must be rejected")
	}
}

func TestSubmitRejectsUnsafeIdentities(t *testing.T) {
	s := newStore(t)
	for _, id := range []string{"../escape", "a/b", "", ".hidden", strings.Repeat("x", 65)} {
		if _, err := s.Submit(id, csrFor(t, id)); err == nil {
			t.Errorf("id %q must be rejected", id)
		}
	}
	if entries, _ := s.List(); len(entries) != 0 {
		t.Errorf("rejected ids must not be stored: %v", entries)
	}
}

func TestResubmitIsIdempotentButKeySwapIsRefused(t *testing.T) {
	s := newStore(t)
	csrPEM := csrFor(t, "web1")
	if _, err := s.Submit("web1", csrPEM); err != nil {
		t.Fatal(err)
	}
	state, err := s.Submit("web1", csrPEM)
	if err != nil {
		t.Fatalf("re-submitting the same request must be a no-op: %v", err)
	}
	if state != StatePending {
		t.Errorf("state = %q, want pending", state)
	}
	if _, err := s.Submit("web1", csrFor(t, "web1")); err == nil {
		t.Fatal("a second, different key for a known id must be refused")
	}
}

func TestSubmitAfterAcceptReportsAccepted(t *testing.T) {
	s := newStore(t)
	csrPEM := csrFor(t, "web1")
	if _, err := s.Submit("web1", csrPEM); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}
	state, err := s.Submit("web1", csrPEM)
	if err != nil {
		t.Fatalf("submit after accept: %v", err)
	}
	if state != StateAccepted {
		t.Errorf("state = %q, want accepted", state)
	}
}

func TestAcceptIsStableAcrossCalls(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	first, err := s.Accept("web1")
	if err != nil {
		t.Fatal(err)
	}
	second, err := s.Accept("web1")
	if err != nil {
		t.Fatalf("re-accepting must return the issued certificate: %v", err)
	}
	if string(first) != string(second) {
		t.Error("accepting twice issued two different certificates")
	}
}

func TestRejectedIdentityIsNotIssuedACertificate(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if err := s.Reject("web1"); err != nil {
		t.Fatalf("reject: %v", err)
	}
	if _, err := s.Accept("web1"); err == nil {
		t.Fatal("a rejected identity must not be acceptable without an operator removing it")
	}
	if _, err := s.IssuedCert("web1"); err == nil {
		t.Fatal("a rejected identity must have no certificate")
	}
}

func TestRemoveLetsAnIdentityStartOver(t *testing.T) {
	s := newStore(t)
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if err := s.Reject("web1"); err != nil {
		t.Fatal(err)
	}
	if err := s.Remove("web1"); err != nil {
		t.Fatalf("remove: %v", err)
	}
	state, err := s.Submit("web1", csrFor(t, "web1"))
	if err != nil {
		t.Fatalf("re-enrolling a removed id: %v", err)
	}
	if state != StatePending {
		t.Errorf("state = %q, want pending", state)
	}
}

func TestListReportsStateAndFingerprint(t *testing.T) {
	s := newStore(t)
	pendingCSR := csrFor(t, "db1")
	if _, err := s.Submit("web1", csrFor(t, "web1")); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Submit("db1", pendingCSR); err != nil {
		t.Fatal(err)
	}
	if _, err := s.Accept("web1"); err != nil {
		t.Fatal(err)
	}

	entries, err := s.List()
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("got %d entries, want 2: %v", len(entries), entries)
	}
	byID := map[string]Entry{}
	for _, e := range entries {
		byID[e.ID] = e
	}
	if byID["web1"].State != StateAccepted || byID["db1"].State != StatePending {
		t.Errorf("wrong states: %v", entries)
	}
	// The accepted certificate must carry the same key the request had.
	want, err := CSRFingerprint(pendingCSR)
	if err != nil {
		t.Fatal(err)
	}
	if byID["db1"].Fingerprint != want {
		t.Errorf("fingerprint = %q, want %q", byID["db1"].Fingerprint, want)
	}
	if byID["web1"].Fingerprint == "" {
		t.Error("accepted entry has no fingerprint")
	}
}

func TestServerCertificateCarriesItsSANs(t *testing.T) {
	s := newStore(t)
	if err := s.IssueServer("master.example.com", []string{"master.example.com", "10.0.0.1"}, time.Hour); err != nil {
		t.Fatalf("issue server: %v", err)
	}
	certPEM, err := os.ReadFile(filepath.Join(s.Dir, "master.crt"))
	if err != nil {
		t.Fatal(err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		t.Fatal(err)
	}
	if len(cert.DNSNames) != 1 || cert.DNSNames[0] != "master.example.com" {
		t.Errorf("dns names = %v", cert.DNSNames)
	}
	if len(cert.IPAddresses) != 1 || cert.IPAddresses[0].String() != "10.0.0.1" {
		t.Errorf("ip sans = %v", cert.IPAddresses)
	}
	info, err := os.Stat(filepath.Join(s.Dir, "master.key"))
	if err != nil {
		t.Fatal(err)
	}
	if mode := info.Mode().Perm(); mode != 0o600 {
		t.Errorf("master.key mode is %04o, want 0600", mode)
	}
}

func TestTamperedCSRIsRejected(t *testing.T) {
	s := newStore(t)
	block, _ := pem.Decode(csrFor(t, "web1"))
	if block == nil {
		t.Fatal("generated CSR is not PEM")
	}
	// Corrupt the trailing signature bytes: the structure still parses, but
	// the requester can no longer prove it holds the private key.
	block.Bytes[len(block.Bytes)-1] ^= 0xff
	tampered := pem.EncodeToMemory(block)

	if _, err := s.Submit("web1", tampered); err == nil {
		t.Fatal("a CSR that fails signature verification must be rejected")
	}
}
