// Package docsaudit holds the generated reference documentation to the
// code it was generated from.
//
// docs/configuration.md and docs/modules.md are written by
// tools/gendocs. Generated documentation that is committed and then not
// checked is worse than none: it is trusted, and it goes stale the first
// time someone adds a module and forgets. This fails when a generated
// file and the code disagree, and the fix is to run the generator.
package docsaudit

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"

	"github.com/edlitmus/halite/internal/builtin"
)

// generated names each file, the go run target that writes it, and a
// short reason for the reader who hits the failure.
var generated = []string{
	"docs/configuration.md",
	"docs/modules.md",
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	return root
}

// Every generated file matches what the generator produces now.
func TestGeneratedDocsAreCurrent(t *testing.T) {
	root := repoRoot(t)
	tmp := t.TempDir()

	cmd := exec.Command("go", "run", "./tools/gendocs", tmp)
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("running the generator failed: %v\n%s", err, out)
	}

	for _, name := range generated {
		want, err := os.ReadFile(filepath.Join(tmp, filepath.Base(name)))
		if err != nil {
			t.Fatalf("the generator did not write %s: %v", name, err)
		}
		got, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			t.Fatalf("%s: %v\nrun: go run ./tools/gendocs docs", name, err)
		}
		if string(got) != string(want) {
			t.Errorf("%s is out of date with the code.\n"+
				"Run `go run ./tools/gendocs docs` and commit the result.\n\n%s",
				name, firstDifference(string(got), string(want)))
		}
	}
}

// A generated file must say so, or someone will edit it by hand and lose
// the edit at the next generation.
func TestGeneratedDocsSaySoAtTheTop(t *testing.T) {
	root := repoRoot(t)
	for _, name := range generated {
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		head := string(data)
		if len(head) > 400 {
			head = head[:400]
		}
		if !strings.Contains(head, "Generated by tools/gendocs") {
			t.Errorf("%s does not say it is generated near the top", name)
		}
	}
}

// firstDifference reports the first line that differs, which is more use
// than a diff of four thousand lines.
func firstDifference(got, want string) string {
	g := strings.Split(got, "\n")
	w := strings.Split(want, "\n")
	for i := 0; i < len(g) || i < len(w); i++ {
		var gl, wl string
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return "first difference at line " + itoa(i+1) + ":\n  committed: " + gl + "\n  generated: " + wl
		}
	}
	return "the files differ in length only"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}

// Every relative link in the documentation resolves.
//
// A documentation set with a broken link is worse than one without the
// link: a reader follows it, finds nothing, and stops trusting the rest.
// This is cheap to check and impossible to remember.
func TestDocumentationLinksResolve(t *testing.T) {
	root := repoRoot(t)
	files := []string{"README.md", "CHANGELOG.md"}
	entries, err := os.ReadDir(filepath.Join(root, "docs"))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".md") {
			files = append(files, filepath.Join("docs", e.Name()))
		}
	}

	link := regexp.MustCompile(`\]\(([^)#][^)]*)\)`)
	for _, name := range files {
		data, err := os.ReadFile(filepath.Join(root, name))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		for _, m := range link.FindAllStringSubmatch(stripCodeSpans(string(data)), -1) {
			target := m[1]
			if strings.HasPrefix(target, "http://") ||
				strings.HasPrefix(target, "https://") ||
				strings.HasPrefix(target, "mailto:") {
				continue
			}
			// A fragment names a heading in the target file; the file is
			// what has to exist.
			path := strings.SplitN(target, "#", 2)[0]
			resolved := filepath.Join(root, filepath.Dir(name), path)
			if _, err := os.Stat(resolved); err != nil {
				t.Errorf("%s links to %q, which does not exist", name, target)
			}
		}
	}
}

// The documentation set is listed in the README, so a page nobody links
// to is a page nobody reads.
func TestEveryDocPageIsLinkedFromTheReadme(t *testing.T) {
	root := repoRoot(t)
	readme, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(filepath.Join(root, "docs"))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if !strings.Contains(string(readme), "docs/"+e.Name()) {
			t.Errorf("docs/%s is not linked from README.md; add it to the table there or remove it",
				e.Name())
		}
	}
}

// stripCodeSpans blanks the contents of inline code and fenced blocks so
// that the link check does not read them. `salt['pillar.get']('a:b')` is
// not a link to a file called 'a:b', and a documented example that
// happens to contain `](` should not have to be rewritten to keep this
// test quiet.
func stripCodeSpans(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	inFence, inSpan := false, false
	for i := 0; i < len(s); i++ {
		if !inSpan && strings.HasPrefix(s[i:], "```") {
			inFence = !inFence
			b.WriteString("```")
			i += 2
			continue
		}
		if !inFence && s[i] == '`' {
			inSpan = !inSpan
			b.WriteByte('`')
			continue
		}
		if inFence || inSpan {
			if s[i] == '\n' {
				// Newlines are kept so that a fence still terminates and
				// the remaining offsets stay recognisable.
				b.WriteByte('\n')
				inSpan = false
				continue
			}
			b.WriteByte(' ')
			continue
		}
		b.WriteByte(s[i])
	}
	return b.String()
}

// TestCountsInProseMatchTheBuild. The generated pages cannot drift
// because they are generated. A sentence in a hand-written page saying
// how many functions ship can, and did: migrating-from-salt.md claimed
// 54 state functions for weeks after there were 56.
//
// Any page that states a count states it in the same shape, so the shape
// is what this looks for.
func TestCountsInProseMatchTheBuild(t *testing.T) {
	root := repoRoot(t)
	r := builtin.New()
	want := map[string]int{
		"execution functions": len(r.Exec.Signatures().Names()),
		"state functions":     len(r.States.Signatures().Names()),
	}
	wantModules := map[string]int{
		"execution functions": countModules(r.Exec.Signatures().Names()),
		"state functions":     countModules(r.States.Signatures().Names()),
	}

	// "209 execution functions across 42 modules", and "56 state
	// functions across 20", where the trailing noun may be left implied.
	pattern := regexp.MustCompile(`(\d+)\s+(execution functions|state functions)\s+across\s+(\d+)`)

	pages, err := filepath.Glob(filepath.Join(root, "docs", "*.md"))
	if err != nil {
		t.Fatal(err)
	}
	pages = append(pages, filepath.Join(root, "README.md"))

	checked := 0
	for _, page := range pages {
		data, err := os.ReadFile(page)
		if err != nil {
			t.Fatal(err)
		}
		for _, m := range pattern.FindAllStringSubmatch(string(data), -1) {
			checked++
			kind := m[2]
			functions, _ := strconv.Atoi(m[1])
			modules, _ := strconv.Atoi(m[3])
			if functions != want[kind] {
				t.Errorf("%s says %d %s; this build has %d",
					filepath.Base(page), functions, kind, want[kind])
			}
			if modules != wantModules[kind] {
				t.Errorf("%s says %d modules for %s; this build has %d",
					filepath.Base(page), modules, kind, wantModules[kind])
			}
		}
	}
	if checked == 0 {
		t.Error("no page states a function count; this check has stopped checking anything")
	}
}

// countModules counts the distinct modules in a list of dotted names.
func countModules(names []string) int {
	seen := map[string]bool{}
	for _, n := range names {
		module, _, _ := strings.Cut(n, ".")
		seen[module] = true
	}
	return len(seen)
}
