// gendocs writes the reference documentation that can be derived from the
// code, so that it cannot drift from it.
//
// The configuration reference comes from internal/config's key table and
// the module reference from the signature registry a build ships. Both are
// checked by internal/docsaudit, which fails when a generated file and the
// code disagree — the same discipline internal/specaudit applies to the
// gap ledger.
//
// Usage: go run ./tools/gendocs <docs-directory>
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/edlitmus/halite/internal/builtin"
	"github.com/edlitmus/halite/internal/config"
	"github.com/edlitmus/halite/internal/signature"
)

const generatedNotice = "<!-- Generated by tools/gendocs. Edit the code, not this file. -->"

func main() {
	dir := "docs"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	write(filepath.Join(dir, "configuration.md"), ConfigurationReference())
	write(filepath.Join(dir, "modules.md"), ModuleReference())
}

func write(path, body string) {
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote", path)
}

// ConfigurationReference renders every configuration key.
func ConfigurationReference() string {
	var b strings.Builder
	b.WriteString("# Configuration reference\n\n")
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString(`Every setting halite reads, which of the three programs reads it, what
it defaults to, and the section of SPEC.md that defines it.

A configuration file is YAML. Settings a program does not read are an
error rather than a typo that does nothing, so a key misspelled or put in
the wrong file is reported at startup:

` + "```yaml\n# <config root>/node.yaml\nnode_id: web1.prod.example.com\nfile_roots:\n  base:\n    - /srv/halite/states\npillar_roots:\n  base:\n    - /srv/halite/pillar\n```" + `

Salt's own names are accepted where they differ, with a warning naming the
halite spelling and the release the compatibility shim is removed in. See
SPEC section 28.3.

## Where the files live

SPEC section 27.3 states the layout in Linux FHS terms, and a BSD keeps a
package's configuration and state elsewhere. The defaults below are
written with a token rather than a path, because the same build reads a
different one depending on where it runs. The configuration root is also
probed for ` + "`state`" + ` and ` + "`pillar`" + ` directories, so a tree
that lives beside the configuration needs no roots set at all.

`)
	b.WriteString("| Token | Linux | FreeBSD, OpenBSD, NetBSD, DragonFly |\n|---|---|---|\n")
	for _, t := range config.PathTable() {
		fmt.Fprintf(&b, "| `%s` | `%s` | `%s` |\n", t.Token, t.Linux, t.BSD)
	}
	b.WriteString("\n")

	roles := []struct {
		role  config.Role
		title string
		intro string
	}{
		{config.Node, "halite-node", "Read by the node agent."},
		{config.Hub, "halite-hub", "Read by the hub."},
		{config.API, "halite-api", "Read by the API service."},
	}
	for _, r := range roles {
		var keys []config.Key
		for _, k := range config.Keys {
			for _, kr := range k.Roles {
				if kr == r.role {
					keys = append(keys, k)
					break
				}
			}
		}
		if len(keys) == 0 {
			continue
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i].Name < keys[j].Name })
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", r.title, r.intro)
		b.WriteString("| Setting | Default | SPEC | Meaning |\n|---|---|---|---|\n")
		for _, k := range keys {
			def := config.PortablePath(k.Default)
			if def == "" {
				def = "—"
			} else {
				def = "`" + def + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				k.Name, def, k.Section, escapePipes(k.Doc))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// ModuleReference renders every module function a build ships.
func ModuleReference() string {
	r := builtin.New()
	var b strings.Builder
	b.WriteString("# Module reference\n\n")
	b.WriteString(generatedNotice + "\n\n")

	execSigs := r.Exec.Signatures()
	stateSigs := r.States.Signatures()
	fmt.Fprintf(&b, `Every function this build ships: %d execution functions across %d
modules, and %d state functions across %d.

The same information is available on a node without reading anything:
`+"`halite-node call sys.list_modules`"+`, `+"`sys.doc`"+` for one function, and
`+"`sys.argspec`"+` for its parameters. SPEC section 15.6.

A parameter is written `+"`name: type`"+`, with a default after `+"`=`"+` when it has
one. An argument is a string unless its type says otherwise, which is what
stops a package version of `+"`1.0`"+` becoming a float — SPEC section 9.2.

What is **not** here is as important as what is: halite ships a subset of
Salt's roughly 400 modules, chosen by what a real estate applies. The gaps
are listed, module by module, in [DIVERGENCE.md](DIVERGENCE.md).

`, len(r.Exec.Names()), len(execSigs.Modules()), len(r.States.Names()), len(stateSigs.Modules()))

	b.WriteString("## Execution modules\n\n")
	writeModules(&b, execSigs)
	b.WriteString("## State modules\n\n")
	b.WriteString("A state function is what an SLS file calls. Each declares whether it\nchanges the system and whether its test mode is reliable; the conformance\nharness of SPEC section 11.6 holds every one of them to that claim.\n\n")
	writeModules(&b, stateSigs)
	return b.String()
}

func writeModules(b *strings.Builder, reg *signature.Registry) {
	for _, module := range reg.Modules() {
		fns := reg.Functions(module)
		sort.Slice(fns, func(i, j int) bool { return fns[i].Function < fns[j].Function })
		fmt.Fprintf(b, "### `%s`\n\n", module)
		for _, s := range fns {
			fmt.Fprintf(b, "#### `%s`\n\n", s.Name())
			if s.Doc != "" {
				fmt.Fprintf(b, "%s\n\n", s.Doc)
			}
			fmt.Fprintf(b, "```\n%s\n```\n\n", signatureLine(s))
			if len(s.Params) > 0 {
				b.WriteString("| Parameter | Type | Default | Meaning |\n|---|---|---|---|\n")
				for _, p := range s.Params {
					def := "—"
					switch {
					case p.Required:
						def = "*required*"
					case p.Default != nil:
						def = fmt.Sprintf("`%v`", p.Default)
					}
					fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n",
						p.Name, p.Type.String(), def, escapePipes(p.Doc))
				}
				b.WriteString("\n")
			}
			if notes := signatureNotes(s); notes != "" {
				fmt.Fprintf(b, "%s\n\n", notes)
			}
		}
	}
}

// signatureLine is the one-line call form, without the doc Describe adds.
func signatureLine(s signature.Signature) string {
	var b strings.Builder
	b.WriteString(s.Name())
	b.WriteByte('(')
	for i, p := range s.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		if p.Variadic {
			b.WriteByte('*')
		}
		fmt.Fprintf(&b, "%s: %s", p.Name, p.Type.String())
		if !p.Required && p.Default != nil {
			fmt.Fprintf(&b, " = %v", p.Default)
		}
	}
	b.WriteByte(')')
	return b.String()
}

func signatureNotes(s signature.Signature) string {
	var notes []string
	if s.Mutates {
		notes = append(notes, "changes the system")
	}
	switch s.TestMode {
	case signature.TestReliable:
		notes = append(notes, "honours `--test`")
	case signature.TestUnreliable:
		notes = append(notes, "**test mode is unreliable here**: what the function does depends on something halite cannot predict")
	}
	if s.ArbitraryCode {
		notes = append(notes, "**runs arbitrary code**")
	}
	if s.Section != "" {
		notes = append(notes, "SPEC section "+s.Section)
	}
	if len(notes) == 0 {
		return ""
	}
	return "*" + strings.Join(notes, " · ") + "*"
}

// escapePipes keeps a doc string from breaking the table it sits in.
func escapePipes(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "|", `\|`), "\n", " ")
}
